name: Cicla
description: "A private-first period tracking app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  drift: ^2.14.1
  sqlcipher_flutter_libs: ^0.5.1
  path_provider: ^2.1.1
  path: ^1.8.3
  easy_localization: ^3.0.3
  flutter_secure_store: ^9.0.0
  local_auth: ^2.1.6
  flutter_local_notifications: ^16.3.0
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/icons/general/
    - assets/icons/health/
    - assets/icons/health/symptoms/
    - assets/icons/health/moods/
    - assets/icons/health/flows/
    - assets/icons/health/discharge/
    - assets/images/
